# Generated by Django 5.1.7 on 2025-03-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
